services:
  - type: web
    name: tour-management-web
    runtime: docker
    plan: free
    region: oregon
    autoDeploy: true

    envVars:
      - key: DB_DRIVER
        value: pgsql
      - key: DB_PORT
        value: "5432"

      - key: EXTERNAL_API_MODE
        value: live

      # Hotels (Amadeus)
      - key: EXTERNAL_HOTEL_API
        value: https://test.api.amadeus.com/v1/reference-data/locations/hotels/by-city
      - key: EXTERNAL_HOTEL_API_TOKEN
        sync: false

      # Restaurants (External partner API)
      - key: EXTERNAL_RESTAURANT_API
        value: https://restaurantmanagement.ct.ws/api
      - key: EXTERNAL_RESTAURANT_API_TOKEN
        sync: false

      # Taxi / ETA
      - key: EXTERNAL_TAXI_API
        value: https://api.openrouteservice.org/v2/directions/driving-car
      - key: EXTERNAL_TAXI_API_KEY
        sync: false

    healthCheckPath: /
